baseURL = "http://localhost:8080/"
languageCode = "en-us"
title = "RHD Front-end Code and Documentation"
theme = "rhd"
publishDir = "../../docs"
canonifyURLs = true
disableFastRender = true

[params]
    Minify = false